firstlovecenter/fl-admin-portal

- api/src/functions/graphql/graphql.js
- api/src/index.js
- api/src/schema.graphql
- web-react/src/pages/BishopSelect.jsx
Removed auth directives to enable me to run queries and mutations without being hampered by failing hasScope directives
> removed auth directives

- api/src/resolvers/campaigns/campaigns-resolver.ts
- api/src/schema/campaigns-equipment.graphql
> fix: add optional match to equipment defaulters queries

- api/src/resolvers/cypher/resolver-cypher.ts
- api/src/resolvers/directory/make-servant-resolvers.ts
- api/src/schema/directory-crud.graphql
- web-react-ts/src/components/DisplayChurchDetails/AdminMutations.ts
- web-react-ts/src/components/DisplayChurchDetails/DisplayChurchDetails.tsx
> feat: implement adding gathering service admin

- api/src/resolvers/campaigns/campaigns-resolver.ts
- api/src/schema/campaigns-equipment.graphql
> fix: fixes errors in equipment campaign defaulters queries

- web-react-ts/src/pages/campaigns/components/buttons/FellowshipTrendsButton.tsx
- web-react-ts/src/pages/campaigns/components/buttons/TrendsButton.tsx
- web-react-ts/src/pages/campaigns/equipment/constituency/ConstituencyEquipmentForm.tsx
- web-react-ts/src/pages/campaigns/equipment/fellowship/FellowshipEquipmentForm.tsx
> Adds validations to the equipment campaign forms to limit user input to 1

- web-react-ts/src/pages/campaigns/CampaignQueries.ts
- web-react-ts/src/pages/campaigns/campaignsRoutes.ts
- web-react-ts/src/pages/campaigns/components/buttons/DefaultersCard.tsx
- web-react-ts/src/pages/campaigns/components/buttons/DefaultersMenuButton.tsx
- web-react-ts/src/pages/campaigns/components/buttons/TrendsButton.css
- web-react-ts/src/pages/campaigns/equipment/constituency/ConstituencyEquipmentCampaign.tsx
- web-react-ts/src/pages/campaigns/equipment/constituency/ConstituencyEquipmentDefaulters.tsx
- web-react-ts/src/pages/campaigns/equipment/constituency/ConstituencyEquipmentHaveNotFilledByFellowship.tsx
- web-react-ts/src/pages/campaigns/equipment/council/CouncilEquipmentCampaign.tsx
- web-react-ts/src/pages/campaigns/equipment/council/CouncilEquipmentDefaulters.tsx
- web-react-ts/src/pages/campaigns/equipment/council/CouncilEquipmentHaveNotFilledByConstituency.tsx
- web-react-ts/src/pages/campaigns/equipment/council/CouncilEquipmentHaveNotFilledByFellowship.tsx
> Implements defaulters flow for equipment campaign

- web-react-ts/src/index.tsx
THIS PROJECT IS IN MAINTENANCE MODE. We accept pull-requests for Bug Fixes **ONLY**. NO NEW FEATURES ACCEPTED!
Sabbath Feature was broken in prod. This PR fixes is so that the sabbath happens as expected.
> fix: correct sabbath timer and adjust so that sabbath starts at 4 am 

- .github/PULL_REQUEST_TEMPLATE.md
- api/BeforeNextUpdate.cypher
- api/src/resolvers/arrivals/arrivals-cypher.ts
- api/src/resolvers/arrivals/arrivals-resolvers.ts
- api/src/schema/arrivals.graphql
- api/src/schema/directory-crud.graphql
- web-react-ts/src/components/DisplayChurchDetails/DisplayChurchDetails.tsx
- web-react-ts/src/components/base-component/ErrorScreen.tsx
- web-react-ts/src/pages/arrivals/BacentaArrivals.tsx
- web-react-ts/src/pages/arrivals/arrivals-types.ts
- web-react-ts/src/pages/arrivals/arrivalsQueries.ts
- web-react-ts/src/pages/directory/directoryRoutes.ts
- web-react-ts/src/pages/directory/display/DetailsBacenta.tsx
- web-react-ts/src/pages/directory/display/DetailsConstituency.tsx
- web-react-ts/src/pages/directory/display/ReadQueries.ts
- web-react-ts/src/pages/directory/reusable-forms/BacentaForm.tsx
- web-react-ts/src/pages/directory/reusable-forms/ConstituencyForm.tsx
- web-react-ts/src/pages/directory/update/UpdateBacentaArrivals.ts
- web-react-ts/src/pages/directory/update/UpdateBusPaymentDetails.tsx
- web-react-ts/src/pages/directory/update/UpdateConstituencyBussingCost.tsx
THIS PROJECT IS IN MAINTENANCE MODE. We accept pull-requests for Bug Fixes **ONLY**. NO NEW FEATURES ACCEPTED!
Implement arrivals 4.1 new changes
Implement bacenta top ups using this scheme 
Costs under 100 receive 50% support
Costs under 220 receive 70% and 
Costs above that receive 80%
Tested on localhost. Since most of the changes were cosmetic changes it was easy to see from the front end.
With the payment function, and end to end test was used to determine that it is working
> feature: implement arrivals 4.1 changes

- api/src/resolvers/campaigns/campaigns-cypher.ts
- api/src/resolvers/campaigns/campaigns-resolver.ts
This PR is an attempt to fixing Equipment Deadline Bug that says "Equipment Deadline Up!"
Refactored the structure of if statement for check for equipment deadline.
> fix: changes structure of check equipment deadline statement

- web-react-ts/public/manifest.json
added list a shortcuts to the manifest.json file
I have not tested my changes , I hope to test with the deploy preview
> feat: add shortcuts feature to pwa for convenient user experience

- api/src/resolvers/arrivals/arrivals-cypher.ts
This PR fixes an issue where a timeNode variable was not defined.
It has not been tested.
> fix: fix arrivals timeNode error

- web-react-ts/src/index.css
…r PWA
I change the font colour of text on the user profile screen to make it more visible
Tested on my local host
> fix: change font colour on user profile screen that is not visible on User profile screen

- api/BeforeNextUpdate.cypher
- api/src/resolvers/cypher/resolver-cypher.ts
- api/src/resolvers/directory/directory-resolvers.ts
- api/src/schema/directory.graphql
This PR implements aggregation on all levels of the church during member registration.
This has been tested and proven to work on my laptop
> feat: admin-273 implement aggregation member count

- web-react-ts/public/manifest.json
Not yet, I will test with a deploy preview 
change the start url in manifest.json to prevent 404 page on initial start
> fix: change start url in manifest.json

- .github/PULL_REQUEST_TEMPLATE.md
- api/src/schema/arrivals.graphql
- api/src/schema/directory-search.graphql
- web-react-ts/src/components/DisplayChurchDetails/DisplayChurchDetails.tsx
- web-react-ts/src/pages/directory/display/DetailsBacenta.tsx
- web-react-ts/src/pages/directory/mobile/SearchPage.tsx
- Removed Trailing Decimal Numbers from Bacenta Top Ups
- Fixed the search so that the arrivals gathering admin can use it
- update PR template
Tested thoroughly on localhost and runs smoothly
> Miscellanous Arrivals Fixes

- web-react-ts/src/pages/campaigns/components/buttons/DefaulterDetailsCard.tsx
…in equipment defaulters flow
before the fix(focus on fotobi constituency)
after the fix
> fix: fix admin names appearing as undefined when no admin is present in equipment defaulters flow

- web-react-ts/src/pages/arrivals/DashboardGatheringService.tsx
show modal pop up to confirm code of the day has been set in arrivals
yes it has been tested on my localhost
https://user-images.githubusercontent.com/36607706/190233512-2a3a4f00-1e10-40a7-a7ec-7c56f7afc537.mov
> fix: show modal pop up to confirm code of the day has been set in arrivals

- api/src/resolvers/cypher/resolver-cypher.ts
- api/src/resolvers/directory/directory-resolvers.ts
- api/src/schema/arrivals.graphql
- api/src/schema/directory-crud.graphql
- api/src/schema/directory.graphql
This PR replaces the static member count and targets.
> fix: replace static target and member count with dynamic counts

- api/src/resolvers/arrivals/arrivals-cypher.ts
> fix: fix cypher that violates creation of aggregatebussing

- api/package-lock.json
- api/package.json
- api/src/functions/graphql/package-lock.json
- api/src/functions/graphql/package.json
- api/src/functions/scheduled-data-aggregation/package-lock.json
Upon updating to neo4j version 3.8.0 we found that many of our pages were breaking due to a bug in the neo4j graphql library. This PR attempts to correct that
No testing as yet, but hoping to do so on the deploy preview
> fix: fix version numbers in packagelock.json

- web-react-ts/src/pages/dashboards/Navigation.css
- web-react-ts/src/pages/dashboards/Navigation.tsx
I added a button for refreshing and going back for better pwa experience 
yes
It has been tested on my local machine
https://user-images.githubusercontent.com/36607706/191434398-0c1e509b-e766-41cb-b6dd-da2fda2353d3.mov
> feat: add a refresh and back button to the navbar

- web-react-ts/src/pages/dashboards/Navigation.tsx
…one mode
conditional render the set back and refresh button to only show when app is in standalone mode
I will test with the deploy preview
> feat: set back and refresh button to only show when app is in standalone mode

- api/BeforeNextUpdate.cypher
- api/package-lock.json
- api/package.json
- api/src/functions/graphql/graphql.js
- api/src/functions/graphql/package-lock.json
- api/src/functions/graphql/package.json
- api/src/index.js
- api/src/resolvers/utils/utils.ts
- package-lock.json
- web-react-ts/package-lock.json
- web-react-ts/package.json
- web-react-ts/src/global-utils.ts
- web-react-ts/src/index.tsx
- web-react-ts/src/pages/dashboards/UserDashboard.tsx
This PR will implement sentry error reporting to enable us to more easily track bugs and crashes from the front end and backend of the app.
Tested rigorously on localhost and looking forward to seeing results in prod
> Implement Integration of Sentry.io Error Reporting

- web-react-ts/src/pages/campaigns/components/buttons/FellowshipTrendsButton.tsx
- web-react-ts/src/pages/campaigns/equipment/bacenta/BacentaByFellowship.tsx
- web-react-ts/src/pages/services/banking/self-banking/FellowshipSelfBanking.tsx
> fix: add optional chain to prevent "cannot read properties of undefined" errors from sentry

- web-react-ts/src/pages/dashboards/Navigation.css
- web-react-ts/src/pages/dashboards/Navigation.tsx
Implement a button behind the refresh and back buttons so that users can see feedback when they interact with the icons
this has been tested on my local machine
https://user-images.githubusercontent.com/36607706/192085338-65e092c0-8660-4954-9393-1d43baa94463.mov
> ADMIN-318 Implement a button behind the refresh and back buttons

- web-react-ts/src/pages/arrivals/FormMobilisationSubmission.tsx
added an optional chain in form mobilisation submission to prevent cannot read property of undefined error
yes on my local machine
> ADMIN-328 add optional chain in form mobilisation submission

- api/src/resolvers/arrivals/arrivals-cypher.ts
> fix: fix bug preventing bussing data from aggregating on higher churches

- api/src/resolvers/arrivals/arrivals-cypher.ts
> fix: add with which was breaking the mutation to record arrival time

- web-react-ts/src/pages/arrivals/ChurchBySubChurch.tsx
> fix: fix arrivals typo breaking the build

- web-react-ts/src/pages/directory/update/UpdateFellowship.tsx
I have tested on my local machine 
https://user-images.githubusercontent.com/36607706/192769942-533e2e45-5ef9-4efc-aaa7-d7ec0517eaa9.mov
> ADMIN-351 fix: fix error where user is unable to edit a fellowship when there is no leader

- api/src/schema/banking.graphql
This PR adds Anagkazo banking as a banking proof so that on the fellowship dashboard banking slip will show as submitted.
> fix: add tellerConfirmationTime as banking proof

- api/src/resolvers/banking/banking-cypher.ts
- api/src/resolvers/banking/banking-resolver.ts
- web-react-ts/src/pages/services/banking/self-banking/FellowshipSelfBanking.tsx
> fix: log record during confirmation

- api/BeforeNextUpdate.cypher
- api/src/resolvers/cypher/resolver-cypher.ts
- api/src/resolvers/directory/directory-resolvers.ts
- api/src/schema/directory-crud.graphql
- api/src/schema/directory-search.graphql
- api/src/schema/directory.graphql
- web-react-ts/src/pages/services/banking/anagkazo/ConfirmAnagkazoBanking.tsx
This PR does three things
1. Adds Cypher to BeforeNextUpdate cypher to set all members to active
2. Ensures that all the places where member lists are called, only :Active:Members are returned
3. Creates a mutation that changes the labels of the Member to Inactive
https://user-images.githubusercontent.com/36535410/193092586-63a33ade-f556-4522-b92e-573fb087f126.mov
> Admin-59 as a stream admin i want to be able to delete members

- api/src/functions/payment/package-lock.json
- api/src/functions/payment/package.json
- api/src/functions/payment/payment.js
- api/src/resolvers/arrivals/arrivals-resolvers.ts
- api/src/resolvers/arrivals/arrivals-types.ts
- api/src/resolvers/banking/banking-cypher.ts
- api/src/resolvers/banking/banking-resolver.ts
- api/src/resolvers/banking/banking-types.ts
- api/src/resolvers/utils/financial-utils.ts
- api/src/resolvers/utils/utils.ts
- api/src/schema/banking.graphql
- api/src/schema/directory.graphql
- api/src/schema/services.graphql
- web-react-ts/src/global-types.ts
- web-react-ts/src/pages/services/banking/self-banking/ConfirmPayment.css
- web-react-ts/src/pages/services/banking/self-banking/FellowshipSelfBanking.tsx
- web-react-ts/src/pages/services/banking/self-banking/PayOffering.tsx
- web-react-ts/src/pages/services/banking/self-banking/bankingQueries.ts
This PR will migrate us from using PaySwitch to PayStack for our mobile money transactions in the church.
Testing is ongoing using the deploy preview
> feat: migrate payment system to paystack

- api/src/functions/payment/payment.js
- api/src/resolvers/banking/banking-resolver.ts
> Paystack debugging

- api/src/resolvers/anagkazo/treasury-resolvers.ts
This PR removes the day checker on anagkazo banking
Testing on deploy preview
> fix: remove day checker on anagkazo banking

- api/src/schema/services.graphql
This PR adds a field to service records that returns the member who banked the offering
> feat: add bankedBy field to service record

- web-react-ts/src/pages/services/banking/anagkazo/ConfirmAnagkazoBanking.tsx
- web-react-ts/src/pages/services/banking/anagkazo/TellerSelect.css
added a spinner inside the popup modal to indicate whether data is available or not
This feature was tested on my local machine
https://user-images.githubusercontent.com/36607706/197326180-d234f22b-dcfa-4ffe-8151-5272e56e6a4a.mov
> fix: place loader in the pop up on confirm anagkazo banking page

- README.md
> chore: edited readme file

- api/src/resolvers/campaigns/campaigns-resolver.ts
- api/src/resolvers/cypher/resolver-cypher.ts
- api/src/resolvers/directory/make-remove-servants.ts
- api/src/resolvers/directory/servant-cypher.ts
- api/src/resolvers/directory/utils.ts
- api/src/resolvers/resolvers.ts
- api/src/resolvers/sheep-seeking/sheep-seeking-resolvers.ts
- api/src/resolvers/utils/types.ts
- api/src/schema/graphql-schema.js
- api/src/schema/sheep-seeking.graphql
- web-react-ts/src/pages/campaigns/StreamCampaigns.tsx
- web-react-ts/src/pages/campaigns/campaignsRoutes.ts
- web-react-ts/src/pages/campaigns/sheep-seeking/stream/ModalSubmitButton.tsx
- web-react-ts/src/pages/campaigns/sheep-seeking/stream/SheepSeekerSelect.tsx
- web-react-ts/src/pages/campaigns/sheep-seeking/stream/SheepSeeking.gql.ts
- web-react-ts/src/pages/campaigns/sheep-seeking/stream/StreamSheepSeekerCampaign.tsx
This PR adds mutations to setup and remove sheep seeker roles
> feat: add make and remove stream sheep seeker mutations

- api/beforeSetupDevInstance.cypher
…nv script
This PR adds to the setup development cypher script and adds all the list of testers and developers as members, and leaves only one string of churches for campus, town and anagkazo.
This has been tested on my local database.
> admin-422-TASK/write-cypher-script-to-create-test-environment-members-and churches

- api/BeforeNextUpdate.cypher
- api/beforeSetupDevInstance.cypher
- api/src/resolvers/arrivals/arrivals-cypher.ts
- api/src/schema/directory-crud.graphql
This PR 
- corrects bacenta.code to bacenta.bacentaCode
- corrects topUp to lpIvyTopUp
- changes lastBacentaCode to one node instead of per stream
- imports codes from existing sheet
> fix: import bacenta codes from Lp Ivy's list

- web-react-ts/src/pages/arrivals/arrival-payment-data/ArrivalsPaymentData.tsx
> fix: add momo number to arrivals payment excel sheet

- api/src/resolvers/arrivals/arrivals-cypher.ts
This PR orders the arrivals payment data sheet by society
> fix: order arrivals payment sheet by society

- web-react-ts/src/pages/services/banking/self-banking/PayOffering.tsx
This PR makes the charges for using self banking visible to the users.
Tested locally.
> admin-451-STORY/show-self-banking-transac

- api/src/resolvers/arrivals/arrivals-cypher.ts
- api/src/schema/arrivals.graphql
- web-react-ts/src/pages/arrivals/arrival-payment-data/ArrivalsPaymentData.tsx
- web-react-ts/src/pages/arrivals/arrivalsQueries.ts
This PR adds momo name to the arrivals payment excel
> fix: add momo name to arrivals payment excel sheet

- web-react-ts/src/index.tsx
This PR makes all GQL queries rertry 5 times before returning error messages this is to handle task timeouts and long running queries.
Tested using localhost dev and is demoed in the loom below
https://www.loom.com/share/c992564a209c48f88852fd6919b214d1
> feat: implement apollo client query retry

- web-react-ts/src/components/ChurchGraph/ChurchGraph.tsx
- web-react-ts/src/components/formik/MultiImageUpload.tsx
- web-react-ts/src/index.css
- web-react-ts/src/pages/campaigns/campaignsRoutes.ts
- web-react-ts/src/pages/campaigns/multiplication/MultiplicationCampaignServiceTrends.tsx
- web-react-ts/src/pages/campaigns/multiplication/MultiplicationQueries.ts
- web-react-ts/src/pages/campaigns/multiplication/constituency/ConstituencyMultiplicationCampaignTrends.tsx
- web-react-ts/src/pages/campaigns/multiplication/council/CouncilMultiplicationCampaignTrends.tsx
- web-react-ts/src/pages/campaigns/multiplication/gathering-service/GatheringServiceMultiplicationCampaignTrends.tsx
- web-react-ts/src/pages/campaigns/multiplication/stream/StreamMultiplicationCampaignTrends.tsx
- web-react-ts/src/pages/dashboards/useComponentQuery.tsx
- web-react-ts/src/pages/services/graphs/graphs-utils.ts
Implements screens so that users can view their multiplication trends after filling their forms 
This was tested on my local machine
Please pardon my bad internet😞
https://www.loom.com/share/0eee9409dbc7496985cdda5e8d543650
> feat: implement multiplication crusade trends

- web-react-ts/src/components/ChurchSearch.jsx
Added functionality to the church search component to search for leaders as well as churches
Yes it has been tested on my local machine
https://www.loom.com/share/815f2e6438db44978e58aea473f14c54
> feat: support search for leaders as well as churches in churchSearch

- api/src/schema/banking.graphql
- web-react-ts/src/global-types.ts
- web-react-ts/src/pages/services/defaulters/ConstituencyNotBankedThisWeek.tsx
- web-react-ts/src/pages/services/defaulters/CouncilNotBankedThisWeek.tsx
- web-react-ts/src/pages/services/defaulters/DefaulterInfoCard.tsx
- web-react-ts/src/pages/services/defaulters/DefaultersDashboard.tsx
- web-react-ts/src/pages/services/defaulters/DefaultersQueries.ts
- web-react-ts/src/pages/services/defaulters/JointServiceDefaultersCard.tsx
- web-react-ts/src/pages/services/defaulters/defaulters-types.ts
- web-react-ts/src/pages/services/servicesRoutes.ts
Implement joint service for constituency and council banking defaulters.
Tested in the dev environments
> Admin 470 story/constituency service defa

- api/src/resolvers/attendance/cypher-attendance.ts
- api/src/resolvers/attendance/utils-attendance.ts
> fix: automate bacenta status

- api/src/resolvers/services/service-cypher.ts
- api/src/resolvers/services/service-resolvers.ts
- api/src/schema/banking.graphql
- api/src/schema/directory.graphql
- api/src/schema/services.graphql
- web-react-ts/src/pages/arrivals/FormAttendanceConfirmation.tsx
- web-react-ts/src/pages/arrivals/FormMobilisationSubmission.tsx
- web-react-ts/src/pages/services/defaulters/ConstituencyBankedThisWeek.tsx
- web-react-ts/src/pages/services/defaulters/ConstituencyNotBankedThisWeek.tsx
- web-react-ts/src/pages/services/defaulters/CouncilBankedThisWeek.tsx
- web-react-ts/src/pages/services/defaulters/DefaulterInfoCard.tsx
- web-react-ts/src/pages/services/defaulters/DefaultersDashboard.tsx
- web-react-ts/src/pages/services/defaulters/DefaultersQueries.ts
- web-react-ts/src/pages/services/defaulters/JointServiceDefaultersCard.tsx
- web-react-ts/src/pages/services/defaulters/defaulters-types.ts
- web-react-ts/src/pages/services/servicesRoutes.ts
Implements cards and pages showing when joint services have  been banked in a particular week.
> Admin 475 story/joint services this week

- web-react-ts/src/components/ChurchGraph/ChurchGraph.tsx
Implemented a loader on the church graph page
I have testes this on my local
https://www.loom.com/share/8e1db8dcdc244f48941a5d579417bdf5
> feat: admin-489 implement a loader on a church graph page

- web-react-ts/src/pages/campaigns/swollen-sunday/bacenta/BacentaSwollenSundayTrends.tsx
- web-react-ts/src/pages/campaigns/swollen-sunday/constituency/ConstituencySwollenSundayTrends.tsx
- web-react-ts/src/pages/campaigns/swollen-sunday/council/CouncilSwollenSundayTrends.tsx
- web-react-ts/src/pages/campaigns/swollen-sunday/gathering-service/GatheringServiceSwollenSundayTrends.tsx
- web-react-ts/src/pages/campaigns/swollen-sunday/stream/StreamSwollenSundayTrends.tsx
Show the swollen sunday graphs when a user opens the swollen sunday page
yes it has been tested on my local machine
https://www.loom.com/share/abdf3ddc3326457b9ffdfb8ba75086c8
> feat: admin-493 show swollen sunday graphs on render

- api/src/resolvers/arrivals/arrivals-cypher.ts
- api/src/resolvers/services/service-cypher.ts
Adds a property containing the ids of all records that are contributing to the aggregate record
> Component-ids

- api/src/schema/arrivals.graphql
- api/src/schema/directory.graphql
- web-react-ts/src/components/AllChurchesSummary.tsx
- web-react-ts/src/components/DisplayChurchDetails/DisplayChurchDetails.tsx
- web-react-ts/src/components/DisplayChurchList.tsx
- web-react-ts/src/components/card/DetailsCard.tsx
- web-react-ts/src/pages/directory/directoryRoutes.ts
- web-react-ts/src/pages/directory/display/AllICs.tsx
- web-react-ts/src/pages/directory/display/DetailsConstituency.tsx
- web-react-ts/src/pages/directory/display/DetailsCouncil.tsx
- web-react-ts/src/pages/directory/display/DetailsFellowship.tsx
- web-react-ts/src/pages/directory/display/DetailsGatheringService.tsx
- web-react-ts/src/pages/directory/display/DetailsOversight.tsx
- web-react-ts/src/pages/directory/display/DetailsStream.tsx
- web-react-ts/src/pages/directory/display/ReadQueries.ts
- web-react-ts/src/queries/ListQueries.ts
added a card so as to show the number of ICs at all level
In has been tested on my local machine 
https://www.loom.com/share/a72ac7bf2ee847a7a05e570c74aa31ef
> Admin 482 story/show ics card

- api/src/schema/campaigns-shepherding-control.graphql
- api/src/schema/graphql-schema.js
- web-react-ts/src/index.css
- web-react-ts/src/pages/campaigns/GatheringServiceCampaigns.tsx
- web-react-ts/src/pages/campaigns/campaignsRoutes.ts
- web-react-ts/src/pages/campaigns/components/inputs/FloatingLabelFormControl.tsx
- web-react-ts/src/pages/campaigns/equipment/gathering-service/GatheringServiceEquipmentCampaign.tsx
- web-react-ts/src/pages/campaigns/equipment/gathering-service/GatheringServiceEquipmentDefaulters.tsx
- web-react-ts/src/pages/campaigns/equipment/gathering-service/GatheringServiceTrends.tsx
- web-react-ts/src/pages/campaigns/multiplication/gathering-service/GatheringServiceMultiplicationCampaign.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/ShepherdingControlLandingPage.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/ShepherdingControlQueries.ts
- web-react-ts/src/pages/campaigns/shepherding-control/bacenta/BacentaShepherdingControlCampaign.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/bacenta/BacentaShepherdingControlYearTillDate.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/constituency/ConstituencyShepherdingControlCampaign.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/constituency/ConstituencyShepherdingControlYearTillDate.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/council/CouncilShepherdingControlCampaign.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/council/CouncilShepherdingControlYearTillDate.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/gathering-service/GatheringServiceShepherdingControlCampaign.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/gathering-service/GatheringServiceShepherdingControlYearTillDate.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/stream/StreamShepherdingControlCampaign.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/stream/StreamShepherdingControlYearTillDate.tsx
Add the Shepherding Control Campaign
It has been tested on my local machine 
https://www.loom.com/share/ae11c9e4b92f4b759e88490ec36af065
> Shepherding control campaign

- web-react-ts/src/pages/campaigns/components/inputs/FloatingLabelFormControl.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/bacenta/BacentaShepherdingControlYearTillDate.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/constituency/ConstituencyShepherdingControlYearTillDate.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/council/CouncilShepherdingControlYearTillDate.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/gathering-service/GatheringServiceShepherdingControlYearTillDate.tsx
- web-react-ts/src/pages/campaigns/shepherding-control/stream/StreamShepherdingControlYearTillDate.tsx
I added commas to separate values in the FloatingLabelFormControl
Yes it has been tested on my local machine
> refactor: separate values in FloatingLabelFormControl with commas

- api/src/resolvers/campaigns/swollen-sunday/swollen-sunday-campaign-resolvers.ts
- web-react-ts/src/pages/campaigns/swollen-sunday/SwollenSundayUploadTargets.tsx
Added a check to prevent users from uploading excel files with null values for swollen sunday target 
Yes this has been tested on my local machine
https://www.loom.com/share/7572b82f1b04437691d4029b33b5c23e
> Admin 488 story/excel uploads checker

- web-react-ts/src/pages/campaigns/CampaignChurchList.tsx
- web-react-ts/src/pages/campaigns/GatheringServiceCampaigns.tsx
- web-react-ts/src/pages/campaigns/campaignsRoutes.ts
- web-react-ts/src/pages/campaigns/swollen-sunday/SwollenSundayLandingPage.tsx
- web-react-ts/src/pages/campaigns/swollen-sunday/SwollenSundayQueries.tsx
- web-react-ts/src/pages/campaigns/swollen-sunday/bacenta/SwollenSundayBacentaList.tsx
- web-react-ts/src/pages/campaigns/swollen-sunday/constituency/SwollenSundayConstituencyList.tsx
- web-react-ts/src/pages/campaigns/swollen-sunday/council/SwollenSundayCouncilList.tsx
- web-react-ts/src/pages/campaigns/swollen-sunday/gathering-service/GatheringServiceSwollenSundayCampaign.tsx
- web-react-ts/src/pages/campaigns/swollen-sunday/gathering-service/GatheringServiceSwollenSundayStreamList.tsx
Added functionality for Gathering service admin to be able to drill down and assign targets to bacentas under various stream
it has been tested on my local macchine
https://www.loom.com/share/61b9d12c8e08458980bfb3734fdcdd8e
> feat: admin-504 implement gathering service swollen sunday drill down

- web-react-ts/src/pages/campaigns/swollen-sunday/SwollenSundayTarget.tsx
added the stream name to swollen sunday target template
I have tested this on my local machine 
https://www.loom.com/share/a264da8473164d39a2fc54912db10ace
> feat: admin-503 add stream name to swollen sunday target template

- web-react-ts/src/pages/arrivals/arrivals-utils.ts
> fix: remove option for private car in bussing form

- api/src/resolvers/campaigns/swollen-sunday/swollen-sunday-campaign-cypher.ts
- api/src/schema/campaigns-swollen-sunday.graphql
This PR fixes the issue with sharing of targets by council. This issue was an issue with the aggregation cypher for the targets.
This has been tested on my localhost.
> fix: admin-509 fix target sharing

- api/src/resolvers/campaigns/campaigns-resolver.ts
- api/src/resolvers/directory/directory-resolvers.ts
- api/src/resolvers/permissions.ts
- web-react-ts/src/components/members-grids/MembersGrid.jsx
- web-react-ts/src/global-types.ts
- web-react-ts/src/pages/campaigns/CampaignChurchList.tsx
- web-react-ts/src/pages/campaigns/campaignsRoutes.ts
- web-react-ts/src/pages/campaigns/sheep-seeking/gathering-service/GatheringServiceSheepSeekerCampaign.tsx
- web-react-ts/src/pages/campaigns/sheep-seeking/stream/StreamSheepSeekerCampaign.tsx
- web-react-ts/src/pages/dashboards/DashboardQueries.ts
- web-react-ts/src/pages/dashboards/dashboard-utils.ts
- web-react-ts/src/pages/dashboards/useComponentQuery.tsx
- web-react-ts/src/pages/dashboards/userChurchDataQueries.ts
- web-react-ts/src/pages/directory/directoryRoutes.ts
- web-react-ts/src/pages/directory/reusable-forms/MemberForm.tsx
- web-react-ts/src/permission-utils.ts
- Created a sheep seeking flow for GatheringService Admin
- Added screens for sheep seeker to add members and view membership
- add sheep seeking to campaign list if the user has stream or sheep seeking permissions
yes this has been tested on my local machine 
https://www.loom.com/share/7981b6fe14e04c95b9974469b933fb22
https://www.loom.com/share/a313b133ba9b43e89b82e234f4e15510
> Admin 498 story/sheep seeking interface

- web-react-ts/src/pages/campaigns/multiplication/MultiplicationCampaignBankingSlipView.tsx
add the NoDataComponent to MultiplicationCampaignBankingSlipView when there is no data
This has been tested on my local machine
> refactor: add NoDataComponent to MultiplicationCampaignBankingSlipView

- api/src/resolvers/campaigns/swollen-sunday/swollen-sunday-campaign-cypher.ts
- api/src/schema/arrivals.graphql
- api/src/schema/campaigns-swollen-sunday.graphql
- api/src/schema/directory.graphql
This PR changes the target property on churches to use the last swell target
https://www.loom.com/share/245ed5ecdad04f37ad01ade12066b051
> fix: change target property on church levels to last swell target

- web-react-ts/src/components/AllChurchesSummary.tsx
This has been tested run my local machine
> fix: fix bug where sontacard does not display numbers

- api/src/resolvers/directory/directory-resolvers.ts
- web-react-ts/src/components/members-grids/MembersGrid.jsx
- web-react-ts/src/pages/campaigns/sheep-seeking/stream/StreamSheepSeekerCampaign.tsx
- web-react-ts/src/pages/directory/directoryRoutes.ts
- web-react-ts/src/pages/directory/reusable-forms/MemberDisplay.tsx
- web-react-ts/src/pages/directory/reusable-forms/MemberForm.tsx
Gives permissions back to Stream Admisn and fellowship leaders to register members
Tested on local
> Admin 518 story/member crud permissions

- api/src/schema/directory.graphql
fix: change hub from object to array
> fix: change hub from object to array

- api/src/schema/basonta-churches.graphql
- api/src/schema/directory.graphql
add member count to hub and ministry
> add member count to hub and ministry

- api/src/schema/basonta-churches.graphql
- api/src/schema/directory.graphql
fix: add relationship between ministry and federalministry
> fix: add relationship between ministry and federalministry

- api/src/schema/directory-basonta.graphql
fix: member basonta queries on member node
> fix: member basonta queries on member node

- api/src/schema/directory-basonta.graphql
- api/src/schema/directory.graphql
> fix: sonta count queries

- api/src/resolvers/cypher/resolver-cypher.ts
- api/src/resolvers/directory/make-servant-resolvers.ts
- api/src/resolvers/directory/servant-cypher.ts
- api/src/resolvers/permissions.ts
- api/src/schema/directory-basonta.graphql
- api/src/schema/directory-crud.graphql
> fix: make leader mutations

- api/src/schema/directory-basonta.graphql
fix: permissions for create mutations
> fix: permissions for create mutations

- api/src/schema/directory.graphql
> Admin  527 fix/sonta queries

- api/src/schema/directory.graphql
> Admin 532 fix/sonta queries

- api/src/resolvers/arrivals/bacenta-status/utils-bacenta-status.ts
- web-react-ts/src/pages/arrivals/FormAttendanceConfirmation.tsx
This PR fixes the bug to change bacenta to graduated when a bacenta busses at least 8 for 4 consecutive weeks. 
I tested this locally. 
https://www.loom.com/share/4ce62767e2c34ca0bcd3173e1cbd84b2
> fix: bacenta status change bug for bussing 8 and above

- api/src/resolvers/arrivals/arrivals-cypher.ts
- api/src/resolvers/arrivals/arrivals-resolvers.ts
- api/src/resolvers/arrivals/bacenta-status/cypher-bacenta-status.ts
- api/src/resolvers/arrivals/bacenta-status/utils-bacenta-status.ts
- api/src/resolvers/texts.json
send sms to bacenta leaders when their bacenta status is graduated from an IC and vice versa
I tested this locally
https://www.loom.com/share/836379e885ca4b3e94540bf2e46ac3bb - Change bacenta status to graduated
https://www.loom.com/share/7b65d25d58df4837b25e4f29e9c4d875 - Change bacenta status to IC
> fix: send sms bacenta status change

- web-react-ts/src/pages/dashboards/userChurchDataQueries.ts
- web-react-ts/src/pages/directory/update/UpdateMutations.ts
remove stream name from hubLeader query and remove constituency from update sonta mutation
> fix: fix issue with update sonta mutation
